// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"tr\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/layout/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " · Mahrec</title><script src=\"https://unpkg.com/htmx.org@2.0.4\"></script><script src=\"https://unpkg.com/idiomorph@0.7.4/dist/idiomorph-ext.min.js\"></script><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin=\"anonymous\"><link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=Outfit:wght@400;500;600;700&display=swap\"><link rel=\"stylesheet\" href=\"/static/css/app.css\"><script>\n\t\t\t\t// Clears a Select's displayed value + list-box selection state; used\n\t\t\t\t// after successfully submitting the new-goal form.\n\t\t\t\tfunction resetSelectVisual(rootId) {\n\t\t\t\t\tvar root = document.getElementById(rootId);\n\t\t\t\t\tif (!root) return;\n\t\t\t\t\tvar value = root.querySelector('[data-slot=\"select-value\"]');\n\t\t\t\t\tif (value) {\n\t\t\t\t\t\tvalue.setAttribute(\"data-placeholder\", \"true\");\n\t\t\t\t\t\tvalue.textContent = value.getAttribute(\"data-placeholder-text\") || \"\";\n\t\t\t\t\t}\n\t\t\t\t\troot.querySelectorAll('[data-slot=\"list-box-item\"]').forEach(function (item) {\n\t\t\t\t\t\titem.removeAttribute(\"data-selected\");\n\t\t\t\t\t\titem.setAttribute(\"aria-selected\", \"false\");\n\t\t\t\t\t\tvar indicator = item.querySelector('[data-slot=\"list-box-item-indicator\"]');\n\t\t\t\t\t\tif (indicator) indicator.removeAttribute(\"data-visible\");\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t</script></head><body class=\"min-h-screen bg-background text-foreground antialiased\" hx-ext=\"morph\"><header class=\"flex items-center justify-center border-b border-separator px-6 py-4\"><a href=\"/\" class=\"text-2xl leading-none text-accent\" style=\"font-family: 'Amiri', serif;\" title=\"Mahrec\" aria-label=\"Mahrec\">مخرج</a></header><main class=\"mx-auto flex max-w-xl flex-col gap-6 p-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><script src=\"/static/js/animations.js\"></script><script src=\"/static/js/alert_dialog.js\"></script><script src=\"/static/js/list_box.js\"></script><script src=\"/static/js/select.js\"></script><script src=\"/static/js/image_zoom.js\"></script><script>\n\t\t\t\t// Server fires this (via HX-Trigger) only when a goal was actually\n\t\t\t\t// created, so a validation error never wipes what the user typed.\n\t\t\t\tdocument.body.addEventListener(\"goal-created\", function () {\n\t\t\t\t\tvar form = document.getElementById(\"goal-form\");\n\t\t\t\t\tif (form) form.reset();\n\t\t\t\t\tvar titleValue = document.getElementById(\"title-value\");\n\t\t\t\t\tif (titleValue) titleValue.value = \"\";\n\t\t\t\t\tresetSelectVisual(\"title-select\");\n\t\t\t\t});\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
